Feature/tags grouping
InvisibleTeam/GoInvisible pull request #112
Opened 2017-02-28 09:59 UTC by michal1990

In this PR exists one ignored test. It will be fixed in the next commit with a missing test.

2017-02-28 10:50 UTC, BartSoftware requested changes

2017-02-28 10:50 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/helper/EditItemAdapterHelper.java
> +            if (IMAGE_INFO.equals(tag.getTagGroupType())) {
switch would fit better

2017-02-28 10:50 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/model/Tag.java
> +    private TagGroupType tagGroupType;
@Nullable

2017-02-28 10:50 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +            return -1;
maybe better is to create some DEFAULT value

2017-02-28 10:50 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +    private EditItemAdapterHelper helper;
final

2017-02-28 10:50 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +    private Context context;
where is this context initialized?

2017-02-28 10:50 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +        if (viewType != -1) {
please make some defalut value, not hardcoded -1, it is used at least in 2 places

2017-02-28 10:50 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +        if (!tagList.isEmpty()) {
if (tagList.isEmpty()) {
return
}

2017-02-28 10:50 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
> +        TagViewHolder holder = (TagViewHolder) adapter.onCreateViewHolder(view, -1);
hardcoded -1

2017-02-28 13:03 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +            return -1;
Switch may be better

2017-02-28 23:18 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/model/Tag.java
> +    private TagGroupType tagGroupType;
It's couldn't be nullable

2017-02-28 23:19 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +    private Context context;
In onCreateViewHolder

2017-02-28 23:19 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/helper/EditItemAdapterHelper.java
> +            if (IMAGE_INFO.equals(tag.getTagGroupType())) {
done

2017-02-28 23:19 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +    private EditItemAdapterHelper helper;
done

2017-02-28 23:20 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +        if (viewType != -1) {
done

2017-02-28 23:22 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +            return -1;
I made a switch with default

2017-02-28 23:23 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapter.java
> +        if (!tagList.isEmpty()) {
done

2017-02-28 23:24 UTC, michal1990 commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
> +        TagViewHolder holder = (TagViewHolder) adapter.onCreateViewHolder(view, -1);
done

2017-03-03 07:20 UTC, BartSoftware requested changes

2017-03-03 07:20 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/model/Tag.java
> +    private TagGroupType tagGroupType;
then there is non necessary condition while reading from parcelable

2017-03-03 07:20 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
> +        ViewGroup parent = new ViewGroup(activity) {
Better is to use some implementation like for example LinearLayout. It helps you avoid unnecessary methods implementation.

2017-03-03 07:20 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/SectionViewHolderTest.java
> +        ViewGroup parent = new ViewGroup(activity) {
LinearLayout

2017-03-03 07:20 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/TagViewHolderTest.java
> +        ViewGroup parent = new ViewGroup(activity) {
LinearLayout

2017-03-03 07:20 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/images/adapter/ImagesItemAdapterTest.java
> +        ViewGroup parent = new ViewGroup(activity) {
LinearLayout

2017-03-06 10:47 UTC, BartSoftware approved these changes

2017-03-06 10:48 UTC, merged