Fix existed and added missed unit tests.
InvisibleTeam/GoInvisible pull request #39
Opened 2017-02-02 10:30 UTC by michal1990

2017-02-02 10:48 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +        if (tag.getKey().equals(TAG_GPS_TIMESTAMP)) {
There is a Timestamp inputType now.

2017-02-02 10:48 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +                case TEXT_STRING:
You have to cover all types.

2017-02-02 10:48 UTC, kejmil01 commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/EditViewModelTest.java
> +    private static final Tag TAG = new Tag("key", "value", TagType.build(InputType.DATE_STRING));
Do you really need this field to be static?

2017-02-02 10:48 UTC, kejmil01 commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditCompoundRecyclerViewTest.java
> +    private static final Tag TAG = new Tag("key", "value", TagType.build(InputType.TEXT_STRING));
Do you need this field to be static?

2017-02-02 10:48 UTC, kejmil01 commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
>          assertThat(adapter.getTagsList(), containsTag(editedTag));
I would check if list size is same as before.

2017-02-03 08:49 UTC, BartSoftware requested changes

2017-02-03 08:49 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/EditViewModelTest.java
>          EditCompoundRecyclerView editCompoundRecyclerView = mock(EditCompoundRecyclerView.class);
I see those 5 lines are boilerplate, maybe move them to method?

2017-02-03 08:49 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
> +    private Tag TAG = new Tag("key", "value", TagType.build(InputType.TEXT_STRING));
final

2017-02-03 10:31 UTC, merged