Feature/edit tags
InvisibleTeam/GoInvisible pull request #42
Opened 2017-02-03 10:57 UTC by michal1990

2017-02-03 11:37 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +                tag.setValue("0.00000");
Did you check if it works? I think NO_VALUE in this case will be same as in TEXT_STRING (empty string).

2017-02-03 11:37 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +                case TIMESTAMP_STRING:
I think we are missing RANGED_STRING here.

2017-02-03 11:59 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +                tag.setValue("0.00000");
Yep, it will be the same, but ranged_string we are using for lat, lng. IMO NO_VALUE for those fields is as good as 0.00000.

2017-02-03 12:01 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +                case TIMESTAMP_STRING:
yep, I will add this

2017-02-03 12:10 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +                tag.setValue("0.00000");
We are using it for lat, lng REF, so user can enter one of the following values: E, W, S, N.  Does this information change your mind about NO_VALUE in  RANGE_STRING case?

2017-02-03 12:51 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +                tag.setValue("0.00000");
yep, it does 🐰

2017-02-03 12:59 UTC, BartSoftware requested changes

2017-02-03 12:59 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +            case RANGED_STRING:
case RANGED_INTEGER:
case VALUE_INTEGER:
                 tag.setValue("0");
                 break;

case RANGED_STRING:
case VALUE_DOUBLE:
                 tag.setValue("0.0");
                 break;

2017-02-03 12:59 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
> +        assertThat(adapter.getTagsList().size(), is(tagList.size()));
Please make matcher for that like for example TagsMatcher

2017-02-03 13:13 UTC, kejmil01 commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
> +        assertThat(adapter.getTagsList().size(), is(tagList.size()));
Well, we should be checking if the list size is same as before updating and if the particular list item was updated.

I can see improvement by storing adapter.getTagsList().size() before update and comparing it after update, but i don't think we need a matcher here.

2017-02-03 13:37 UTC, BartSoftware requested changes

2017-02-03 13:37 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/adapter/EditItemAdapterTest.java
> +        assertThat(adapter.getTagsList().size(), is(tagList.size()));
The matcher should be for all boolean flags in those assertion, i made comment in wrong place

2017-02-06 08:22 UTC, BartSoftware approved these changes

2017-02-06 08:33 UTC, merged