Created util class for parsing rational type to double and string.
InvisibleTeam/GoInvisible pull request #52
Opened 2017-02-08 12:54 UTC by michal1990

2017-02-08 13:14 UTC, BartSoftware requested changes

2017-02-08 13:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/util/TagUtil.java
> +    public static final int SIX_DECIMAL_NUMBER_SCALE = 6;
This should be on top of class

2017-02-08 13:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/util/TagUtil.java
> +        return new StringBuilder()
This looks like some duplication of code.
Maybe better is to expose method for that and append missing part from other place?

2017-02-08 13:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/util/TagUtil.java
> +        result[1] = (int) (60 * (value - result[0]));
Looks like "60", "3600" are used in few places, maybe some constant?

2017-02-08 13:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/util/TagUtil.java
> +        return Long.valueOf(bigString);
This removes dot form double, why?

2017-02-08 13:14 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/util/TagUtilTest.java
> +    public void whenDoubleGPSIsGiven_GeoGPSWillBeReturn() {
please keep our naming convention:
"whenDoubleGPSIsGiven_GeoGPSIsReturned()"

2017-02-08 13:14 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/util/TagUtilTest.java
> +        //given
Given

2017-02-08 13:14 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/util/TagUtilTest.java
> +        //when
When

2017-02-08 13:14 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/util/TagUtilTest.java
> +        //then
Then

2017-02-08 13:41 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/util/TagUtil.java
> +        return new StringBuilder()
Some parts of this builder are duplicated in the second method but I don't think that we should expose method for that.

2017-02-10 11:54 UTC, kejmil01 commented on app/src/main/res/layout/edit_item_view.xml
> +                android:layout_width="170dp"
I think we need to add ellipsize (end) attribute here.

2017-02-13 11:09 UTC, kejmil01 approved these changes

2017-02-13 11:33 UTC, BartSoftware requested changes

2017-02-13 11:33 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/model/GeolocationTag.java
> +    public void setSecondKey(String secondKey) {
VisibleForTesting

2017-02-13 11:33 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
> +        exifInterface.saveAttributes();
This should be fired once at end for changing tags

2017-02-13 11:33 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/util/TagUtil.java
> +        double result = degrees + minutes / HOUR_IN_MINUTES + seconds / HOUR_IN_SECONDS;
There is util for parse minutes for seconds etc. (for ex. TimeUnit.SECONDS.toMillis)

2017-02-13 12:57 UTC, BartSoftware requested changes

2017-02-13 12:57 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/util/TagUtil.java
> +        return rational == null || rational.length() == 0 || !rational.contains("/");
( rational == null || rational.length() == 0 ) -> TextUtils.isEmpty(rational)

2017-02-13 12:57 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/util/TagUtilTest.java
> +
Redundant line

2017-02-13 14:31 UTC, BartSoftware approved these changes

2017-02-13 14:31 UTC, merged