Feature/uia permission tests
InvisibleTeam/GoInvisible pull request #61
Opened 2017-02-14 14:46 UTC by nlesniewski

2017-02-14 15:35 UTC, BartSoftware requested changes

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/Config.java
> + * Created by nlesniewski on 14.02.2017.
Please remove this

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/UiDeviceProvider.java
> + * Created by nlesniewski on 14.02.2017.
Please remove this

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/FileView.java
> + * Created by nlesniewski on 14.02.2017.
Please remove this

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/FileView.java
> +    public static Boolean isOpened() {
I understand that isOpened concerns FileView but what FileView is?

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/MissingPermissionsDialog.java
> + * Created by nlesniewski on 14.02.2017.
Please remove this

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/MissingPermissionsDialog.java
> +    private static final BySelector missingPermissionsTitleSelector = By.res(GOINVISIBLE_PACKAGE, "alertTitle");
Please write all constants with Upper Case (MISSING_PERMISSIONS_TITLE_SELECTOR)

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/UiDialog.java
> +    protected static String GOINVISIBLE_PACKAGE = Config.GOINVISIBLE_PACKAGE;
final

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/UiDialog.java
> +    protected static int TIMEOUT = Config.LAUNCH_TIMEOUT;
final

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/UiDialog.java
> +    protected static UiDevice mDevice = UiDeviceProvider.getInstance();
final

2017-02-14 15:35 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/system/SystemPermissionDialog.java
> + * Created by nlesniewski on 14.02.2017.
Please remove this

2017-02-14 16:02 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/FileView.java
> +    public static Boolean isOpened() {
FileView  is the list of images.

2017-02-15 08:53 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/system/SystemPermissionDialog.java
> + * Created by nlesniewski on 14.02.2017.
:white_check_mark:

2017-02-15 08:53 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/MissingPermissionsDialog.java
> + * Created by nlesniewski on 14.02.2017.
:white_check_mark:

2017-02-15 08:53 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/FileView.java
> + * Created by nlesniewski on 14.02.2017.
:white_check_mark:

2017-02-15 08:53 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/UiDeviceProvider.java
> + * Created by nlesniewski on 14.02.2017.
:white_check_mark:

2017-02-15 08:53 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/Config.java
> + * Created by nlesniewski on 14.02.2017.
:white_check_mark:

2017-02-15 08:55 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/FileView.java
> +    public static Boolean isOpened() {
:white_check_mark:

2017-02-15 09:04 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/MissingPermissionsDialog.java
> +    private static final BySelector missingPermissionsTitleSelector = By.res(GOINVISIBLE_PACKAGE, "alertTitle");
private static final

2017-02-15 09:05 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/UiDialog.java
> +    protected static String GOINVISIBLE_PACKAGE = Config.GOINVISIBLE_PACKAGE;
:white_check_mark:

2017-02-15 09:05 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/UiDialog.java
> +    protected static int TIMEOUT = Config.LAUNCH_TIMEOUT;
:white_check_mark:

2017-02-15 09:06 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/pages/UiDialog.java
> +    protected static UiDevice mDevice = UiDeviceProvider.getInstance();
:white_check_mark:

2017-02-15 10:06 UTC, BartSoftware submitted a review, later dismissed

2017-02-15 10:06 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/UiDeviceProvider.java
> +    private static UiDevice ourInstance = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
maybe applicationInstance/appInstance is a better name?

2017-02-15 10:55 UTC, kejmil01 approved these changes

2017-02-15 11:42 UTC, nlesniewski commented on app/src/androidTest/java/com/invisibleteam/goinvisible/UiDeviceProvider.java
> +    private static UiDevice ourInstance = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
Didn't bothered at all:
- it was automatically generated
- it is private
- whole class is 15 lines of code and no functionality

It is not even a trivial

2017-02-15 13:54 UTC, michal1990 approved these changes

2017-02-15 14:11 UTC, merged