Place picker tests
InvisibleTeam/GoInvisible pull request #68
Opened 2017-02-15 14:57 UTC by kejmil01

TODO:
- edit activity tests

2017-02-15 15:15 UTC, BartSoftware requested changes

2017-02-15 15:15 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisherTest.java
> +    public void whereConnectionIsRequestedAndApiClientIsBuild_GoogleApiConnectIsCalled() {
when*

2017-02-15 15:15 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisherTest.java
> +        //when
When, Then, Given (everywhere)

2017-02-15 17:14 UTC, BartSoftware requested changes

2017-02-15 17:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisher.java
> +    protected GoogleApiClient googleApiClient;
package protected

2017-02-15 17:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisher.java
> +    protected GoogleApiClient.OnConnectionFailedListener buildConnectionFailedListener() {
package protected

2017-02-15 17:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisher.java
> +    protected GoogleApiClient.ConnectionCallbacks buildConnectionCallbacks() {
package protected

2017-02-15 17:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GpsEstablisher.java
> +    protected static final int GPS_REQUEST_CODE_DEFAULT = 1234;
package protected

2017-02-15 17:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GpsEstablisher.java
> +    protected PendingResult<LocationSettingsResult> buildLocationSettingsResult() {
package protected

2017-02-15 17:14 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GpsEstablisher.java
> +    protected void startResolutionForResult(Status status) throws IntentSender.SendIntentException {
package protected

2017-02-15 18:57 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisher.java
> +    protected GoogleApiClient googleApiClient;
Could you explain this request?

2017-02-16 08:43 UTC, michal1990 approved these changes

2017-02-16 08:45 UTC, BartSoftware approved these changes

2017-02-16 10:43 UTC, merged