Place picker refactor and tests.
InvisibleTeam/GoInvisible pull request #70
Opened 2017-02-16 10:53 UTC by kejmil01

2017-02-16 11:11 UTC, BartSoftware requested changes

2017-02-16 11:11 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/GpsEstablisher.java
> +    int getGpsRequestCode() {
Redundant

2017-02-16 11:11 UTC, BartSoftware commented on app/src/main/res/values/strings.xml
> +    <string name="google_api_connection_error">Could not connect with google api.</string>
Could not connect to google api.

2017-02-16 11:11 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisherTest.java
> +    public void whenGoogleApiBuildAndConnected_ApiIsConnected() {
whenGoogleApiIsBuiltAndConnected_ApiIsConnected

2017-02-16 11:11 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisherTest.java
> +    public void whenConnectionRequested_ApiClientBuild() {
whenConnectionIsRequested_ApiClientIsBuilt

2017-02-16 11:11 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisherTest.java
> +    public void whenOnConnectedInvoked_ListenerOnSuccessCalled() {
whenOnConnectedIsInvoked_ListenerOnSuccessIsCalled

2017-02-16 11:11 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GpsEstablisherTest.java
> +        //given
//Given

2017-02-16 14:01 UTC, BartSoftware requested changes

2017-02-16 14:01 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GoogleLocationApiEstablisherTest.java
> +    public void whenOnConnectedIsInvokedAndThereIsNoListener_ErrorisNotThrown() {
whenOnConnectedIsInvokedAndThereIsNoListener_ErrorIsNotThrown

2017-02-16 14:01 UTC, BartSoftware commented on app/src/test/java/com/invisibleteam/goinvisible/mvvm/edition/GpsEstablisherTest.java
> +        GpsEstablisher.StatusListener statusListener = mock(GpsEstablisher.StatusListener.class);
BoilerPlate code, please move it for some method

2017-02-16 19:48 UTC, BartSoftware approved these changes

2017-02-17 08:55 UTC, michal1990 approved these changes

2017-02-17 09:48 UTC, BartSoftware requested changes

2017-02-17 09:48 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/EditActivity.java
> +    protected void onDestroy() {
onDestroy() is not a good idea, its not called every time, much better is onStop()

2017-02-17 10:05 UTC, BartSoftware approved these changes

2017-02-17 10:32 UTC, merged