Unmodifiable tag message. Error snackbar instead of dialog.
InvisibleTeam/GoInvisible pull request #75
Opened 2017-02-17 12:31 UTC by kejmil01

TODO:
- tests

2017-02-17 13:00 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/EditActivity.java
> +            } else if (tag.getTagType().getInputType().equals(InputType.UNMODIFIABLE)) {
better approach is comparing enum value with sth - we are securing against NUllPointerException

2017-02-17 13:00 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/EditActivity.java
>              if (tag.getKey().equals(ExifInterface.TAG_GPS_LATITUDE)) {
better approach is comparing constant value with sth - we are securing against NUllPointerException

2017-02-17 13:00 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/EditActivity.java
> +            } else if (tag.getTagType().getInputType().equals(InputType.INDEFINITE)) {
better approach is comparing enum value with sth - we are securing against NUllPointerException

2017-02-17 13:00 UTC, michal1990 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/dialog/DialogFactory.java
>          binding.valueTextLayout.setError("Error");
by the occasion, can You move this string to res?

2017-02-20 09:26 UTC, BartSoftware requested changes

2017-02-20 09:26 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/EditActivity.java
> +    private void showSnackBar(int unmodifiable_tag_message) {
Please camelCase

2017-02-20 10:26 UTC, BartSoftware approved these changes

2017-02-20 10:34 UTC, michal1990 approved these changes

2017-02-20 10:34 UTC, merged