Feature/uia images pull test
InvisibleTeam/GoInvisible pull request #86
Opened 2017-02-21 12:12 UTC by nlesniewski

2017-02-21 13:38 UTC, BartSoftware requested changes

2017-02-21 13:38 UTC, BartSoftware commented on app/src/androidTest/java/com/invisibleteam/goinvisible/utilities/StorageManagementHelper.java
> +                e.printStackTrace();
Please use Log.e instead of e.printStackTrace();

2017-02-22 08:52 UTC, BartSoftware approved these changes

2017-02-22 08:58 UTC, michal1990 approved these changes

2017-02-22 09:01 UTC, kejmil01 approved these changes

2017-02-22 09:23 UTC, merged