Feature/fix lazy saving
InvisibleTeam/GoInvisible pull request #94
Opened 2017-02-22 16:16 UTC by michal1990

2017-02-22 19:44 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
>      boolean editTag(Tag tag) {
Why is this method boolean, when it is always returning true value?

2017-02-22 19:44 UTC, kejmil01 commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
>      public boolean clearTags(List<Tag> tagsList) {
Why is this method boolean, when it is always returning true value?

2017-02-23 07:24 UTC, BartSoftware requested changes

2017-02-23 07:24 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
>      public boolean clearTags(List<Tag> tagsList) {
+1

2017-02-23 07:24 UTC, BartSoftware commented on app/src/main/java/com/invisibleteam/goinvisible/mvvm/edition/TagsManager.java
>      boolean editTag(Tag tag) {
+1

2017-02-23 09:42 UTC, kejmil01 approved these changes

2017-02-23 09:43 UTC, BartSoftware approved these changes

2017-02-23 09:48 UTC, merged